print("O P E R A Ç Õ E S M A T E M Á T I C A S")
print("M E N U ")
print("1 soma")
print("2 subtracao")
print("3 multiplicacao")
print("4 divisao")
print("5 par ou impar")
print("6 fatorial")
print("primo")
print("digite sair para encerrar.")
print("soma")
n1=int(input("digite um numero:"))
n2=int(input("digite outro numero:"))
resultado=n1+n2
print("o resultado da soma é")